spring.application.name=uni_connect
server.port=8080
spring.security.user.name=admin
spring.security.user.password=1234

# ====== RDS (PostgreSQL) ======
spring.datasource.url=jdbc:postgresql://uniconnect.cri4yyouailh.ap-northeast-2.rds.amazonaws.com:5432/uniconnect?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# oauth
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=openid,profile,email
oauth2.success-redirect=/
oauth2.failure-redirect=/auth/login?error
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
spring.security.oauth2.client.provider.google.user-name-attribute=sub

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

Flyway (migration script place: src/main/resources/db/migration)
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true
spring.flyway.validate-on-migrate=true
spring.flyway.baseline-version=1
spring.flyway.clean-disabled=true
spring.flyway.repair=true

# Encoding
spring.jpa.properties.hibernate.connection.characterEncoding=UTF-8
spring.jpa.properties.hibernate.connection.useUnicode=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

## ====== S3 ======
app.s3.bucket=uniconnect-250909
# (optional) LocalStack / custom endpoint
#spring.cloud.aws.s3.endpoint=http://localhost:4566
spring.cloud.aws.s3.path-style-access-enabled=false

# multipart limits if you accept uploads
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

# ====== log ======
logging.level.org.springframework=INFO
logging.level.org.springframework.security=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.software.amazon.awssdk=INFO
# ? OAuth ?? ?? ??? ??
logging.level.com.uniConnect.member.security.oauth=DEBUG

##env
spring.config.import=optional:file:.env[.properties]
spring.cloud.aws.region.static=ap-northeast-2
spring.cloud.aws.credentials.access-key=${AWS_ACCESS_KEY_ID}
spring.cloud.aws.credentials.secret-key=${AWS_SECRET_ACCESS_KEY}

# JWT
jwt.secret=${JWT_SECRET}
# 30min, 14days (msec)
jwt.access-expiration=1800000
jwt.refresh-expiration=1209600000
