spring.application.name=uni_connect
server.port=8080
spring.security.user.name=admin
spring.security.user.password=1234


# ====== RDS (PostgreSQL) ======
spring.datasource.url=jdbc:postgresql://uniconnect.cri4yyouailh.ap-northeast-2.rds.amazonaws.com:5432/uniconnect?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

# Flyway (migration script place: src/main/resources/db/migration)
spring.flyway.enabled=false
#spring.flyway.locations=classpath:db/migration

## ====== S3 ======
app.s3.bucket=uniconnect-250909
# (optional) LocalStack / custom endpoint
#spring.cloud.aws.s3.endpoint=http://localhost:4566
spring.cloud.aws.s3.path-style-access-enabled=false

# multipart limits if you accept uploads
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

# ====== log ======
logging.level.org.springframework=INFO
logging.level.org.springframework.security=DEBUG
logging.level.org.hibernate.SQL=INFO
logging.level.software.amazon.awssdk=INFO

##env
#spring.config.import=optional:file:.env[.properties]

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=3600000