--
-- PostgreSQL database dump
--

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: admin_metrics; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.admin_metrics (
    total_campaigns integer,
    total_exposure integer,
    total_samples integer,
    metric_id bigint NOT NULL,
    updated_at timestamp(6) without time zone,
    roi_case character varying(100)
);


ALTER TABLE public.admin_metrics OWNER TO postgres;

--
-- Name: admin_metrics_metric_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.admin_metrics ALTER COLUMN metric_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.admin_metrics_metric_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: banners; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.banners (
    is_active boolean,
    banner_id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    description text,
    image_url text,
    link_url text
);


ALTER TABLE public.banners OWNER TO postgres;

--
-- Name: banners_banner_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.banners ALTER COLUMN banner_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.banners_banner_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: business_registrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.business_registrations (
    open_date date,
    registration_id bigint NOT NULL,
    user_id bigint,
    verified_at timestamp(6) without time zone,
    registration_no character varying(20),
    verified_status character varying(20),
    biz_item character varying(50),
    biz_type character varying(50),
    representative_name character varying(50),
    company_name character varying(100),
    certificate_url text,
    CONSTRAINT business_registrations_verified_status_check CHECK (((verified_status)::text = ANY ((ARRAY['Pending'::character varying, 'Verified'::character varying, 'Rejected'::character varying])::text[])))
);


ALTER TABLE public.business_registrations OWNER TO postgres;

--
-- Name: business_registrations_registration_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.business_registrations ALTER COLUMN registration_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.business_registrations_registration_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: campaign_hashtags; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.campaign_hashtags (
    campaign_id bigint,
    hashtag_id bigint,
    id bigint NOT NULL
);


ALTER TABLE public.campaign_hashtags OWNER TO postgres;

--
-- Name: campaign_hashtags_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.campaign_hashtags ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.campaign_hashtags_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: campaign_industries; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.campaign_industries (
    campaign_id bigint,
    id bigint NOT NULL,
    industry_id bigint
);


ALTER TABLE public.campaign_industries OWNER TO postgres;

--
-- Name: campaign_industries_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.campaign_industries ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.campaign_industries_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: campaign_targets; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.campaign_targets (
    campaign_id bigint,
    hashtag_id bigint,
    target_id bigint NOT NULL,
    hashtag_category character varying(30),
    CONSTRAINT campaign_targets_hashtag_category_check CHECK (((hashtag_category)::text = ANY ((ARRAY['Basic'::character varying, 'Interest'::character varying, 'Event'::character varying])::text[])))
);


ALTER TABLE public.campaign_targets OWNER TO postgres;

--
-- Name: campaign_targets_target_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.campaign_targets ALTER COLUMN target_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.campaign_targets_target_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: campaigns; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.campaigns (
    distributed_quantity integer,
    end_date date,
    etc_cost integer,
    is_deleted boolean,
    labor_cost integer,
    product_quantity integer,
    start_date date,
    total_cost integer,
    campaign_id bigint NOT NULL,
    company_id bigint,
    created_at timestamp(6) without time zone,
    student_org_id bigint,
    updated_at timestamp(6) without time zone,
    status character varying(30),
    brand_name character varying(100),
    product_name character varying(100),
    name character varying(120),
    location_name character varying(150),
    target_desc character varying(200),
    purpose text,
    CONSTRAINT campaigns_status_check CHECK (((status)::text = ANY ((ARRAY['InTransit'::character varying, 'OnHold'::character varying, 'Processing'::character varying, 'Rejecting'::character varying, 'Completed'::character varying])::text[])))
);


ALTER TABLE public.campaigns OWNER TO postgres;

--
-- Name: campaigns_campaign_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.campaigns ALTER COLUMN campaign_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.campaigns_campaign_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: collaboration_proposals; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.collaboration_proposals (
    company_id bigint,
    created_at timestamp(6) without time zone,
    industry_id bigint,
    proposal_id bigint NOT NULL,
    phone character varying(20),
    status character varying(20),
    contact_name character varying(60),
    name character varying(100),
    email character varying(120),
    content text,
    proposal_url text,
    CONSTRAINT collaboration_proposals_status_check CHECK (((status)::text = ANY ((ARRAY['Pending'::character varying, 'Reviewed'::character varying, 'Approved'::character varying, 'Rejected'::character varying])::text[])))
);


ALTER TABLE public.collaboration_proposals OWNER TO postgres;

--
-- Name: collaboration_proposals_proposal_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.collaboration_proposals ALTER COLUMN proposal_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.collaboration_proposals_proposal_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: collaboration_reports; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.collaboration_reports (
    approved_at timestamp(6) without time zone,
    collaboration_id bigint,
    created_at timestamp(6) without time zone,
    report_id bigint NOT NULL,
    uploaded_at timestamp(6) without time zone,
    status character varying(30),
    report_title character varying(200),
    file_url text,
    CONSTRAINT collaboration_reports_status_check CHECK (((status)::text = ANY ((ARRAY['Submitted'::character varying, 'WaitingApproval'::character varying, 'Approved'::character varying])::text[])))
);


ALTER TABLE public.collaboration_reports OWNER TO postgres;

--
-- Name: collaboration_reports_report_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.collaboration_reports ALTER COLUMN report_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.collaboration_reports_report_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: collaboration_tasks; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.collaboration_tasks (
    deadline date,
    collaboration_id bigint,
    task_id bigint NOT NULL,
    updated_at timestamp(6) without time zone,
    status character varying(20),
    updated_by character varying(20),
    type character varying(30),
    CONSTRAINT collaboration_tasks_status_check CHECK (((status)::text = ANY ((ARRAY['Pending'::character varying, 'InProgress'::character varying, 'Done'::character varying])::text[]))),
    CONSTRAINT collaboration_tasks_type_check CHECK (((type)::text = ANY ((ARRAY['ProductInfo'::character varying, 'ContentShare'::character varying, 'ShippingInfo'::character varying, 'Receipt'::character varying])::text[])))
);


ALTER TABLE public.collaboration_tasks OWNER TO postgres;

--
-- Name: collaboration_tasks_task_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.collaboration_tasks ALTER COLUMN task_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.collaboration_tasks_task_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: collaborations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.collaborations (
    admin_contract_approved_at timestamp(6) without time zone,
    collaboration_id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    matching_id bigint,
    student_signed_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    status character varying(20),
    contract_url text,
    CONSTRAINT collaborations_status_check CHECK (((status)::text = ANY ((ARRAY['Ready'::character varying, 'InProgress'::character varying, 'WaitingReceipt'::character varying, 'Completed'::character varying])::text[])))
);


ALTER TABLE public.collaborations OWNER TO postgres;

--
-- Name: collaborations_collaboration_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.collaborations ALTER COLUMN collaboration_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.collaborations_collaboration_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: companies; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.companies (
    is_deleted boolean,
    company_id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    industry_id bigint,
    main_contact_id bigint,
    updated_at timestamp(6) without time zone,
    user_id bigint,
    brand_name character varying(100),
    logo_url text
);


ALTER TABLE public.companies OWNER TO postgres;

--
-- Name: companies_company_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.companies ALTER COLUMN company_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.companies_company_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: company_contacts; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.company_contacts (
    is_main boolean,
    company_id bigint,
    contact_id bigint NOT NULL,
    phone character varying(20),
    name character varying(60),
    email character varying(120)
);


ALTER TABLE public.company_contacts OWNER TO postgres;

--
-- Name: company_contacts_contact_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.company_contacts ALTER COLUMN contact_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.company_contacts_contact_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: company_profiles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.company_profiles (
    company_id bigint,
    profile_id bigint NOT NULL,
    description text,
    sns_url character varying(255),
    website character varying(255)
);


ALTER TABLE public.company_profiles OWNER TO postgres;

--
-- Name: company_profiles_profile_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.company_profiles ALTER COLUMN profile_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.company_profiles_profile_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: company_settings; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.company_settings (
    email_notify boolean,
    payment_notify boolean,
    sms_notify boolean,
    company_id bigint,
    setting_id bigint NOT NULL
);


ALTER TABLE public.company_settings OWNER TO postgres;

--
-- Name: company_settings_setting_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.company_settings ALTER COLUMN setting_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.company_settings_setting_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: content_uploads; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.content_uploads (
    collaboration_id bigint,
    upload_id bigint NOT NULL,
    uploaded_at timestamp(6) without time zone,
    uploader_type character varying(20),
    caption text,
    image_url text,
    CONSTRAINT content_uploads_uploader_type_check CHECK (((uploader_type)::text = ANY ((ARRAY['Company'::character varying, 'StudentOrg'::character varying, 'Admin'::character varying])::text[])))
);


ALTER TABLE public.content_uploads OWNER TO postgres;

--
-- Name: content_uploads_upload_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.content_uploads ALTER COLUMN upload_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.content_uploads_upload_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: contracts; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.contracts (
    company_signed boolean NOT NULL,
    is_deleted boolean,
    student_signed boolean NOT NULL,
    company_signed_at timestamp(6) without time zone,
    contract_id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    matching_id bigint,
    receipt_signed_at timestamp(6) without time zone,
    student_signed_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    status character varying(50) NOT NULL,
    company_signature_file_url text,
    pdf_url text,
    receipt_pdf_url text,
    receipt_signature_file_url text,
    signature_file_url text,
    CONSTRAINT contracts_status_check CHECK (((status)::text = ANY ((ARRAY['PendingSignature'::character varying, 'StudentSigned'::character varying, 'Signed'::character varying, 'ReceiptPending'::character varying, 'ReceiptSigned'::character varying])::text[])))
);


ALTER TABLE public.contracts OWNER TO postgres;

--
-- Name: contracts_contract_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.contracts ALTER COLUMN contract_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.contracts_contract_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: email_verifications; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.email_verifications (
    user_id bigint,
    verification_id bigint NOT NULL,
    verified_at timestamp(6) without time zone,
    code character varying(20),
    email character varying(120)
);


ALTER TABLE public.email_verifications OWNER TO postgres;

--
-- Name: email_verifications_verification_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.email_verifications ALTER COLUMN verification_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.email_verifications_verification_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: file_uploads; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.file_uploads (
    created_at timestamp(6) without time zone,
    file_id bigint NOT NULL,
    uploader_id bigint,
    mime_type character varying(50),
    type character varying(50),
    file_url text
);


ALTER TABLE public.file_uploads OWNER TO postgres;

--
-- Name: file_uploads_file_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.file_uploads ALTER COLUMN file_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.file_uploads_file_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.hashtags (
    hashtag_id bigint NOT NULL,
    category character varying(30),
    name character varying(100),
    CONSTRAINT hashtags_category_check CHECK (((category)::text = ANY ((ARRAY['Basic'::character varying, 'Interest'::character varying, 'Event'::character varying])::text[])))
);


ALTER TABLE public.hashtags OWNER TO postgres;

--
-- Name: hashtags_hashtag_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.hashtags ALTER COLUMN hashtag_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.hashtags_hashtag_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: industries; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.industries (
    industry_id bigint NOT NULL,
    name character varying(50)
);


ALTER TABLE public.industries OWNER TO postgres;

--
-- Name: industries_industry_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.industries ALTER COLUMN industry_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.industries_industry_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: invoices; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.invoices (
    invoice_id bigint NOT NULL,
    issued_at timestamp(6) without time zone,
    payment_id bigint,
    issue_type character varying(20),
    registration_no character varying(20),
    biz_item character varying(50),
    biz_type character varying(50),
    representative_name character varying(60),
    company_name character varying(100),
    email character varying(120),
    address character varying(200),
    issued_pdf_url text,
    CONSTRAINT invoices_issue_type_check CHECK (((issue_type)::text = ANY ((ARRAY['Tax'::character varying, 'Cash'::character varying])::text[])))
);


ALTER TABLE public.invoices OWNER TO postgres;

--
-- Name: invoices_invoice_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.invoices ALTER COLUMN invoice_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.invoices_invoice_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: local_credentials; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.local_credentials (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    login_id character varying(255) NOT NULL,
    password_hash character varying(255) NOT NULL
);


ALTER TABLE public.local_credentials OWNER TO postgres;

--
-- Name: local_credentials_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.local_credentials ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.local_credentials_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: login_audits; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.login_audits (
    success boolean,
    audit_id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    user_id bigint,
    ip character varying(45),
    device_info character varying(100)
);


ALTER TABLE public.login_audits OWNER TO postgres;

--
-- Name: login_audits_audit_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.login_audits ALTER COLUMN audit_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.login_audits_audit_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: matching_messages; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.matching_messages (
    created_at timestamp(6) without time zone,
    matching_id bigint,
    message_id bigint NOT NULL,
    sender_type character varying(20),
    message text,
    CONSTRAINT matching_messages_sender_type_check CHECK (((sender_type)::text = ANY ((ARRAY['Company'::character varying, 'Student'::character varying, 'Admin'::character varying])::text[])))
);


ALTER TABLE public.matching_messages OWNER TO postgres;

--
-- Name: matching_messages_message_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.matching_messages ALTER COLUMN message_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.matching_messages_message_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: matching_requests; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.matching_requests (
    expected_participants integer,
    expected_reach integer,
    campaign_id bigint,
    matching_id bigint NOT NULL,
    requested_at timestamp(6) without time zone,
    responded_at timestamp(6) without time zone,
    student_org_id bigint,
    status character varying(20),
    CONSTRAINT matching_requests_status_check CHECK (((status)::text = ANY ((ARRAY['Requested'::character varying, 'Approved'::character varying, 'Rejected'::character varying])::text[])))
);


ALTER TABLE public.matching_requests OWNER TO postgres;

--
-- Name: matching_requests_matching_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.matching_requests ALTER COLUMN matching_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.matching_requests_matching_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notifications; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.notifications (
    is_read boolean NOT NULL,
    created_at timestamp(6) without time zone,
    notification_id bigint NOT NULL,
    related_id bigint,
    message text,
    receiver_role character varying(255) NOT NULL,
    related_entity character varying(255),
    title character varying(255) NOT NULL,
    type character varying(255) NOT NULL,
    CONSTRAINT notifications_type_check CHECK (((type)::text = ANY ((ARRAY['ReportSubmitted'::character varying, 'ReportApproved'::character varying, 'CollaborationUpdate'::character varying, 'ContractSigned'::character varying, 'SamplingRequest'::character varying, 'SystemAlert'::character varying])::text[])))
);


ALTER TABLE public.notifications OWNER TO postgres;

--
-- Name: notifications_notification_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.notifications ALTER COLUMN notification_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notifications_notification_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: oauth_accounts; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.oauth_accounts (
    id bigint NOT NULL,
    linked_at timestamp(6) with time zone,
    user_id bigint NOT NULL,
    email character varying(255),
    picture_url character varying(255),
    provider character varying(255) NOT NULL,
    provider_user_id character varying(255) NOT NULL,
    refresh_token_enc character varying(255)
);


ALTER TABLE public.oauth_accounts OWNER TO postgres;

--
-- Name: oauth_accounts_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.oauth_accounts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.oauth_accounts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: partnership_requests; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.partnership_requests (
    company_id bigint,
    created_at timestamp(6) without time zone,
    industry_id bigint,
    partnership_id bigint NOT NULL,
    phone character varying(20),
    status character varying(20),
    contact_name character varying(60),
    name character varying(100),
    email character varying(120),
    content text,
    hashtags text,
    proposal_url text,
    CONSTRAINT partnership_requests_status_check CHECK (((status)::text = ANY ((ARRAY['Pending'::character varying, 'Reviewed'::character varying, 'Approved'::character varying, 'Rejected'::character varying])::text[])))
);


ALTER TABLE public.partnership_requests OWNER TO postgres;

--
-- Name: partnership_requests_partnership_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.partnership_requests ALTER COLUMN partnership_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.partnership_requests_partnership_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: payment_methods; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.payment_methods (
    is_default boolean,
    company_id bigint,
    method_id bigint NOT NULL,
    expiry character varying(10),
    type character varying(20),
    bank_name character varying(50),
    cvc_enc character varying(50),
    holder_name character varying(50),
    account_no_enc character varying(255),
    card_number_enc character varying(255),
    CONSTRAINT payment_methods_type_check CHECK (((type)::text = ANY ((ARRAY['Card'::character varying, 'Account'::character varying, 'SimplePay'::character varying])::text[])))
);


ALTER TABLE public.payment_methods OWNER TO postgres;

--
-- Name: payment_methods_method_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.payment_methods ALTER COLUMN method_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payment_methods_method_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: payments; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.payments (
    amount integer,
    campaign_id bigint,
    company_id bigint,
    created_at timestamp(6) without time zone,
    method_id bigint,
    payment_id bigint NOT NULL,
    status character varying(20),
    CONSTRAINT payments_status_check CHECK (((status)::text = ANY ((ARRAY['Success'::character varying, 'Canceled'::character varying, 'Refunded'::character varying])::text[])))
);


ALTER TABLE public.payments OWNER TO postgres;

--
-- Name: payments_payment_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.payments ALTER COLUMN payment_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payments_payment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: phone_verifications; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.phone_verifications (
    user_id bigint,
    verification_id bigint NOT NULL,
    verified_at timestamp(6) without time zone,
    code character varying(10),
    phone character varying(20)
);


ALTER TABLE public.phone_verifications OWNER TO postgres;

--
-- Name: phone_verifications_verification_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.phone_verifications ALTER COLUMN verification_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.phone_verifications_verification_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: product_infos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.product_infos (
    delivery_date date,
    is_shipped boolean,
    quantity integer,
    collaboration_id bigint,
    created_at timestamp(6) without time zone,
    product_info_id bigint NOT NULL,
    provided_by character varying(20),
    tracking_no character varying(50),
    product_name character varying(100),
    description text,
    image_url text,
    logo_url text,
    CONSTRAINT product_infos_provided_by_check CHECK (((provided_by)::text = ANY ((ARRAY['Company'::character varying, 'StudentOrg'::character varying, 'Admin'::character varying])::text[])))
);


ALTER TABLE public.product_infos OWNER TO postgres;

--
-- Name: product_infos_product_info_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.product_infos ALTER COLUMN product_info_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.product_infos_product_info_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: qna_answers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.qna_answers (
    admin_id bigint,
    answer_id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    question_id bigint,
    content text
);


ALTER TABLE public.qna_answers OWNER TO postgres;

--
-- Name: qna_answers_answer_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.qna_answers ALTER COLUMN answer_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.qna_answers_answer_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: qna_questions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.qna_questions (
    created_at timestamp(6) without time zone,
    question_id bigint NOT NULL,
    user_id bigint,
    status character varying(20),
    title character varying(200),
    content text,
    password_hash character varying(255),
    CONSTRAINT qna_questions_status_check CHECK (((status)::text = ANY ((ARRAY['Waiting'::character varying, 'Answered'::character varying])::text[])))
);


ALTER TABLE public.qna_questions OWNER TO postgres;

--
-- Name: qna_questions_question_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.qna_questions ALTER COLUMN question_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.qna_questions_question_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: receipt_confirmations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.receipt_confirmations (
    approved_at timestamp(6) without time zone,
    collaboration_id bigint,
    receipt_id bigint NOT NULL,
    submitted_at timestamp(6) without time zone,
    status character varying(30),
    location character varying(255),
    receipt_image_url text,
    receiver_name character varying(255),
    CONSTRAINT receipt_confirmations_status_check CHECK (((status)::text = ANY ((ARRAY['PendingUpload'::character varying, 'WaitingApproval'::character varying, 'Approved'::character varying])::text[])))
);


ALTER TABLE public.receipt_confirmations OWNER TO postgres;

--
-- Name: receipt_confirmations_receipt_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.receipt_confirmations ALTER COLUMN receipt_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.receipt_confirmations_receipt_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: receipts; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.receipts (
    company_signed boolean,
    student_signed boolean,
    document_id bigint NOT NULL,
    matching_id bigint,
    signed_at timestamp(6) without time zone,
    status character varying(30),
    pdf_url text
);


ALTER TABLE public.receipts OWNER TO postgres;

--
-- Name: receipts_document_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.receipts ALTER COLUMN document_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.receipts_document_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: refund_requests; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.refund_requests (
    refund_amount integer,
    payment_id bigint,
    refund_id bigint NOT NULL,
    requested_at timestamp(6) without time zone,
    requester_phone character varying(20),
    bank_name character varying(50),
    holder_name character varying(50),
    requester_name character varying(50),
    requester_email character varying(120),
    account_no_enc character varying(255),
    reason text
);


ALTER TABLE public.refund_requests OWNER TO postgres;

--
-- Name: refund_requests_refund_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.refund_requests ALTER COLUMN refund_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.refund_requests_refund_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sampling_report_feedback; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.sampling_report_feedback (
    is_positive boolean,
    created_at timestamp(6) without time zone,
    feedback_id bigint NOT NULL,
    report_id bigint,
    quote text
);


ALTER TABLE public.sampling_report_feedback OWNER TO postgres;

--
-- Name: sampling_report_feedback_feedback_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.sampling_report_feedback ALTER COLUMN feedback_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sampling_report_feedback_feedback_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sampling_report_media; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.sampling_report_media (
    created_at timestamp(6) without time zone,
    media_id bigint NOT NULL,
    report_id bigint,
    caption character varying(255),
    media_type character varying(255),
    media_url character varying(255),
    CONSTRAINT sampling_report_media_media_type_check CHECK (((media_type)::text = ANY ((ARRAY['IMAGE'::character varying, 'VIDEO'::character varying])::text[])))
);


ALTER TABLE public.sampling_report_media OWNER TO postgres;

--
-- Name: sampling_report_media_media_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.sampling_report_media ALTER COLUMN media_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sampling_report_media_media_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sampling_reports; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.sampling_reports (
    billing_fee integer,
    billing_remaining integer,
    billing_total integer,
    distributed_quantity integer NOT NULL,
    exposure_count integer,
    nps_score integer,
    preference_score double precision,
    purchase_intent_pct double precision,
    reach_count integer,
    sns_mentions integer,
    total_quantity integer NOT NULL,
    unit_price integer,
    campaign_id bigint,
    created_at timestamp(6) without time zone,
    report_id bigint NOT NULL,
    survey_id bigint,
    updated_at timestamp(6) without time zone,
    age_dist_json json,
    brand_name character varying(255) NOT NULL,
    competitor_benchmark character varying(255),
    event_name character varying(255) NOT NULL,
    gender_dist_json json,
    heatmap_json json,
    improvement_suggestions text,
    industry_benchmark character varying(255),
    kpi_charts_json json,
    location character varying(255) NOT NULL,
    negative_summary text,
    period character varying(255) NOT NULL,
    positive_summary text,
    pricing_formula character varying(255),
    product_name character varying(255) NOT NULL,
    refund_info character varying(255),
    report_pdf_url character varying(255),
    roi_estimate character varying(255),
    school_dist_json json,
    status character varying(255) NOT NULL,
    survey_stats_json json,
    target character varying(255) NOT NULL,
    CONSTRAINT sampling_reports_status_check CHECK (((status)::text = ANY ((ARRAY['PendingApproval'::character varying, 'Approved'::character varying, 'Rejected'::character varying])::text[])))
);


ALTER TABLE public.sampling_reports OWNER TO postgres;

--
-- Name: sampling_reports_report_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.sampling_reports ALTER COLUMN report_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sampling_reports_report_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sampling_request; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.sampling_request (
    event_end_date date,
    event_start_date date,
    requested_quantity integer,
    created_at timestamp(6) without time zone NOT NULL,
    sampling_request_id bigint NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    user_id bigint NOT NULL,
    phone character varying(20),
    status character varying(20) NOT NULL,
    industry character varying(30),
    contact_name character varying(50),
    org_name character varying(100),
    school_name character varying(100),
    email character varying(120),
    event_title character varying(150),
    event_description character varying(500),
    proposal_file_url character varying(255),
    CONSTRAINT sampling_request_industry_check CHECK (((industry)::text = ANY ((ARRAY['Fnb'::character varying, 'Beauty'::character varying, 'Education'::character varying, 'OnlineService'::character varying, 'Stationery'::character varying, 'It'::character varying, 'Travel'::character varying])::text[]))),
    CONSTRAINT sampling_request_status_check CHECK (((status)::text = ANY ((ARRAY['Draft'::character varying, 'Submitted'::character varying, 'Approved'::character varying, 'Rejected'::character varying, 'ContractPending'::character varying, 'ContractApprovalPending'::character varying, 'ReceiptPending'::character varying, 'ReceiptApprovalPending'::character varying, 'ReportPending'::character varying, 'ReportApprovalPending'::character varying, 'SurveyPending'::character varying, 'Completed'::character varying])::text[])))
);


ALTER TABLE public.sampling_request OWNER TO postgres;

--
-- Name: sampling_request_sampling_request_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.sampling_request ALTER COLUMN sampling_request_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sampling_request_sampling_request_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sampling_target_keyword; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.sampling_target_keyword (
    is_active boolean NOT NULL,
    target_keyword_id bigint NOT NULL,
    category character varying(20) NOT NULL,
    label character varying(100) NOT NULL,
    description character varying(255),
    CONSTRAINT sampling_target_keyword_category_check CHECK (((category)::text = ANY ((ARRAY['BasicInfo'::character varying, 'Lifestyle'::character varying, 'EventNature'::character varying, 'IndustryOfficial'::character varying])::text[])))
);


ALTER TABLE public.sampling_target_keyword OWNER TO postgres;

--
-- Name: sampling_target_keyword_target_keyword_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.sampling_target_keyword ALTER COLUMN target_keyword_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sampling_target_keyword_target_keyword_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sampling_target_selection; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.sampling_target_selection (
    sampling_request_id bigint NOT NULL,
    selection_id bigint NOT NULL,
    target_keyword_id bigint NOT NULL,
    category character varying(20) NOT NULL,
    selected_label character varying(100),
    CONSTRAINT sampling_target_selection_category_check CHECK (((category)::text = ANY ((ARRAY['BasicInfo'::character varying, 'Lifestyle'::character varying, 'EventNature'::character varying, 'IndustryOfficial'::character varying])::text[])))
);


ALTER TABLE public.sampling_target_selection OWNER TO postgres;

--
-- Name: sampling_target_selection_selection_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.sampling_target_selection ALTER COLUMN selection_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sampling_target_selection_selection_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: shipping_info; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.shipping_info (
    is_shipped boolean,
    shipping_date date,
    collaboration_id bigint NOT NULL,
    id bigint NOT NULL,
    note character varying(255),
    tracking_number character varying(255)
);


ALTER TABLE public.shipping_info OWNER TO postgres;

--
-- Name: shipping_info_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.shipping_info ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.shipping_info_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: student_org_availabilities; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.student_org_availabilities (
    end_date date,
    exposure_count integer,
    recommended_sample_qty integer,
    start_date date,
    availability_id bigint NOT NULL,
    student_org_id bigint,
    event_type character varying(60),
    target_age_range character varying(60),
    event_name character varying(120),
    host_name character varying(120),
    place character varying(120),
    target_major character varying(120),
    target_interest character varying(200),
    description text,
    efficiency_metric text,
    event_points text,
    promotion_plan text,
    promotion_process text
);


ALTER TABLE public.student_org_availabilities OWNER TO postgres;

--
-- Name: student_org_availabilities_availability_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.student_org_availabilities ALTER COLUMN availability_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.student_org_availabilities_availability_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: student_org_contacts; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.student_org_contacts (
    contact_id bigint NOT NULL,
    student_org_id bigint,
    phone character varying(20),
    name character varying(60),
    email character varying(120)
);


ALTER TABLE public.student_org_contacts OWNER TO postgres;

--
-- Name: student_org_contacts_contact_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.student_org_contacts ALTER COLUMN contact_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.student_org_contacts_contact_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: student_org_histories; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.student_org_histories (
    campaign_id bigint,
    history_id bigint NOT NULL,
    student_org_id bigint,
    role character varying(20),
    status character varying(20),
    CONSTRAINT student_org_histories_role_check CHECK (((role)::text = ANY ((ARRAY['Host'::character varying, 'Partner'::character varying])::text[]))),
    CONSTRAINT student_org_histories_status_check CHECK (((status)::text = ANY ((ARRAY['Ongoing'::character varying, 'Done'::character varying])::text[])))
);


ALTER TABLE public.student_org_histories OWNER TO postgres;

--
-- Name: student_org_histories_history_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.student_org_histories ALTER COLUMN history_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.student_org_histories_history_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: student_org_keywords; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.student_org_keywords (
    hashtag_id bigint,
    keyword_id bigint NOT NULL,
    student_org_id bigint
);


ALTER TABLE public.student_org_keywords OWNER TO postgres;

--
-- Name: student_org_keywords_keyword_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.student_org_keywords ALTER COLUMN keyword_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.student_org_keywords_keyword_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: student_orgs; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.student_orgs (
    safety_flag boolean,
    verification_level integer,
    student_org_id bigint NOT NULL,
    phone character varying(20),
    collaboration_type character varying(30),
    organization_type character varying(30),
    manager_name character varying(60),
    school_name character varying(100),
    email character varying(120),
    organization_name character varying(120),
    logo_url text
);


ALTER TABLE public.student_orgs OWNER TO postgres;

--
-- Name: student_orgs_student_org_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.student_orgs ALTER COLUMN student_org_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.student_orgs_student_org_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: student_receive_info; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.student_receive_info (
    collaboration_id bigint NOT NULL,
    id bigint NOT NULL,
    note character varying(255),
    receive_place character varying(255),
    receiver_name character varying(255)
);


ALTER TABLE public.student_receive_info OWNER TO postgres;

--
-- Name: student_receive_info_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.student_receive_info ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.student_receive_info_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: survey; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.survey (
    created_at timestamp(6) without time zone,
    student_org_id bigint,
    survey_id bigint NOT NULL,
    updated_at timestamp(6) without time zone,
    description character varying(255),
    external_link character varying(255),
    status character varying(255),
    title character varying(255),
    CONSTRAINT survey_status_check CHECK (((status)::text = ANY ((ARRAY['Pending'::character varying, 'Submitted'::character varying, 'Approved'::character varying, 'Rejected'::character varying])::text[])))
);


ALTER TABLE public.survey OWNER TO postgres;

--
-- Name: survey_reports; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.survey_reports (
    preference_score double precision,
    purchase_intent_pct double precision,
    reach_count integer,
    created_at timestamp(6) without time zone,
    report_id bigint NOT NULL,
    survey_id bigint,
    updated_at timestamp(6) without time zone,
    report_pdf_url character varying(255)
);


ALTER TABLE public.survey_reports OWNER TO postgres;

--
-- Name: survey_reports_report_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.survey_reports ALTER COLUMN report_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.survey_reports_report_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: survey_responses; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.survey_responses (
    created_at timestamp(6) without time zone,
    response_id bigint NOT NULL,
    survey_id bigint,
    respondent_type character varying(20),
    file_url text,
    summary_text text
);


ALTER TABLE public.survey_responses OWNER TO postgres;

--
-- Name: survey_responses_response_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.survey_responses ALTER COLUMN response_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.survey_responses_response_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: survey_survey_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.survey ALTER COLUMN survey_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.survey_survey_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: survey_templates; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.survey_templates (
    campaign_id bigint,
    created_at timestamp(6) without time zone,
    survey_id bigint NOT NULL,
    title character varying(100),
    file_url text,
    form_url text
);


ALTER TABLE public.survey_templates OWNER TO postgres;

--
-- Name: survey_templates_survey_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.survey_templates ALTER COLUMN survey_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.survey_templates_survey_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    created_at timestamp(6) without time zone,
    student_org_id bigint,
    user_id bigint NOT NULL,
    role character varying(20),
    status character varying(20),
    username character varying(50) NOT NULL,
    password_hash character varying(255),
    CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['Admin'::character varying, 'Company'::character varying, 'StudentOrg'::character varying])::text[]))),
    CONSTRAINT users_status_check CHECK (((status)::text = ANY ((ARRAY['Active'::character varying, 'Suspended'::character varying])::text[])))
);


ALTER TABLE public.users OWNER TO postgres;

--
-- Name: users_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN user_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: admin_metrics admin_metrics_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.admin_metrics
    ADD CONSTRAINT admin_metrics_pkey PRIMARY KEY (metric_id);


--
-- Name: banners banners_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.banners
    ADD CONSTRAINT banners_pkey PRIMARY KEY (banner_id);


--
-- Name: business_registrations business_registrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.business_registrations
    ADD CONSTRAINT business_registrations_pkey PRIMARY KEY (registration_id);


--
-- Name: campaign_hashtags campaign_hashtags_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.campaign_hashtags
    ADD CONSTRAINT campaign_hashtags_pkey PRIMARY KEY (id);


--
-- Name: campaign_industries campaign_industries_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.campaign_industries
    ADD CONSTRAINT campaign_industries_pkey PRIMARY KEY (id);


--
-- Name: campaign_targets campaign_targets_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.campaign_targets
    ADD CONSTRAINT campaign_targets_pkey PRIMARY KEY (target_id);


--
-- Name: campaigns campaigns_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.campaigns
    ADD CONSTRAINT campaigns_pkey PRIMARY KEY (campaign_id);


--
-- Name: collaboration_proposals collaboration_proposals_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.collaboration_proposals
    ADD CONSTRAINT collaboration_proposals_pkey PRIMARY KEY (proposal_id);


--
-- Name: collaboration_reports collaboration_reports_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.collaboration_reports
    ADD CONSTRAINT collaboration_reports_pkey PRIMARY KEY (report_id);


--
-- Name: collaboration_tasks collaboration_tasks_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.collaboration_tasks
    ADD CONSTRAINT collaboration_tasks_pkey PRIMARY KEY (task_id);


--
-- Name: collaborations collaborations_matching_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.collaborations
    ADD CONSTRAINT collaborations_matching_id_key UNIQUE (matching_id);


--
-- Name: collaborations collaborations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.collaborations
    ADD CONSTRAINT collaborations_pkey PRIMARY KEY (collaboration_id);


--
-- Name: companies companies_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.companies
    ADD CONSTRAINT companies_pkey PRIMARY KEY (company_id);


--
-- Name: company_contacts company_contacts_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.company_contacts
    ADD CONSTRAINT company_contacts_pkey PRIMARY KEY (contact_id);


--
-- Name: company_profiles company_profiles_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.company_profiles
    ADD CONSTRAINT company_profiles_pkey PRIMARY KEY (profile_id);


--
-- Name: company_settings company_settings_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.company_settings
    ADD CONSTRAINT company_settings_pkey PRIMARY KEY (setting_id);


--
-- Name: content_uploads content_uploads_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.content_uploads
    ADD CONSTRAINT content_uploads_pkey PRIMARY KEY (upload_id);


--
-- Name: contracts contracts_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.contracts
    ADD CONSTRAINT contracts_pkey PRIMARY KEY (contract_id);


--
-- Name: email_verifications email_verifications_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.email_verifications
    ADD CONSTRAINT email_verifications_pkey PRIMARY KEY (verification_id);


--
-- Name: file_uploads file_uploads_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.file_uploads
    ADD CONSTRAINT file_uploads_pkey PRIMARY KEY (file_id);
--
-- Name: hashtags hashtags_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.hashtags
    ADD CONSTRAINT hashtags_pkey PRIMARY KEY (hashtag_id);


--
-- Name: industries industries_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.industries
    ADD CONSTRAINT industries_pkey PRIMARY KEY (industry_id);


--
-- Name: invoices invoices_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.invoices
    ADD CONSTRAINT invoices_pkey PRIMARY KEY (invoice_id);


--
-- Name: local_credentials local_credentials_login_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.local_credentials
    ADD CONSTRAINT local_credentials_login_id_key UNIQUE (login_id);


--
-- Name: local_credentials local_credentials_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.local_credentials
    ADD CONSTRAINT local_credentials_pkey PRIMARY KEY (id);


--
-- Name: local_credentials local_credentials_user_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.local_credentials
    ADD CONSTRAINT local_credentials_user_id_key UNIQUE (user_id);


--
-- Name: login_audits login_audits_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.login_audits
    ADD CONSTRAINT login_audits_pkey PRIMARY KEY (audit_id);


--
-- Name: matching_messages matching_messages_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.matching_messages
    ADD CONSTRAINT matching_messages_pkey PRIMARY KEY (message_id);


--
-- Name: matching_requests matching_requests_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.matching_requests
    ADD CONSTRAINT matching_requests_pkey PRIMARY KEY (matching_id);


--
-- Name: notifications notifications_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_pkey PRIMARY KEY (notification_id);


--
-- Name: oauth_accounts oauth_accounts_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.oauth_accounts
    ADD CONSTRAINT oauth_accounts_pkey PRIMARY KEY (id);


--
-- Name: oauth_accounts oauth_accounts_provider_email_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.oauth_accounts
    ADD CONSTRAINT oauth_accounts_provider_email_key UNIQUE (provider, email);


--
-- Name: oauth_accounts oauth_accounts_provider_provider_user_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.oauth_accounts
    ADD CONSTRAINT oauth_accounts_provider_provider_user_id_key UNIQUE (provider, provider_user_id);


--
-- Name: partnership_requests partnership_requests_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.partnership_requests
    ADD CONSTRAINT partnership_requests_pkey PRIMARY KEY (partnership_id);


--
-- Name: payment_methods payment_methods_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.payment_methods
    ADD CONSTRAINT payment_methods_pkey PRIMARY KEY (method_id);


--
-- Name: payments payments_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT payments_pkey PRIMARY KEY (payment_id);


--
-- Name: phone_verifications phone_verifications_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.phone_verifications
    ADD CONSTRAINT phone_verifications_pkey PRIMARY KEY (verification_id);


--
-- Name: product_infos product_infos_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.product_infos
    ADD CONSTRAINT product_infos_pkey PRIMARY KEY (product_info_id);


--
-- Name: qna_answers qna_answers_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.qna_answers
    ADD CONSTRAINT qna_answers_pkey PRIMARY KEY (answer_id);


--
-- Name: qna_questions qna_questions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.qna_questions
    ADD CONSTRAINT qna_questions_pkey PRIMARY KEY (question_id);


--
-- Name: receipt_confirmations receipt_confirmations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.receipt_confirmations
    ADD CONSTRAINT receipt_confirmations_pkey PRIMARY KEY (receipt_id);


--
-- Name: receipts receipts_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.receipts
    ADD CONSTRAINT receipts_pkey PRIMARY KEY (document_id);


--
-- Name: refund_requests refund_requests_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.refund_requests
    ADD CONSTRAINT refund_requests_pkey PRIMARY KEY (refund_id);


--
-- Name: sampling_report_feedback sampling_report_feedback_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sampling_report_feedback
    ADD CONSTRAINT sampling_report_feedback_pkey PRIMARY KEY (feedback_id);


--
-- Name: sampling_report_media sampling_report_media_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sampling_report_media
    ADD CONSTRAINT sampling_report_media_pkey PRIMARY KEY (media_id);


--
-- Name: sampling_reports sampling_reports_campaign_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sampling_reports
    ADD CONSTRAINT sampling_reports_campaign_id_key UNIQUE (campaign_id);


--
-- Name: sampling_reports sampling_reports_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sampling_reports
    ADD CONSTRAINT sampling_reports_pkey PRIMARY KEY (report_id);


--
-- Name: sampling_request sampling_request_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sampling_request
    ADD CONSTRAINT sampling_request_pkey PRIMARY KEY (sampling_request_id);


--
-- Name: sampling_target_keyword sampling_target_keyword_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sampling_target_keyword
    ADD CONSTRAINT sampling_target_keyword_pkey PRIMARY KEY (target_keyword_id);


--
-- Name: sampling_target_selection sampling_target_selection_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sampling_target_selection
    ADD CONSTRAINT sampling_target_selection_pkey PRIMARY KEY (selection_id);


--
-- Name: shipping_info shipping_info_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.shipping_info
    ADD CONSTRAINT shipping_info_pkey PRIMARY KEY (id);


--
-- Name: student_org_availabilities student_org_availabilities_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.student_org_availabilities
    ADD CONSTRAINT student_org_availabilities_pkey PRIMARY KEY (availability_id);


--
-- Name: student_org_contacts student_org_contacts_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.student_org_contacts
    ADD CONSTRAINT student_org_contacts_pkey PRIMARY KEY (contact_id);


--
-- Name: student_org_histories student_org_histories_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.student_org_histories
    ADD CONSTRAINT student_org_histories_pkey PRIMARY KEY (history_id);


--
-- Name: student_org_keywords student_org_keywords_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.student_org_keywords
    ADD CONSTRAINT student_org_keywords_pkey PRIMARY KEY (keyword_id);


--
-- Name: student_orgs student_orgs_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.student_orgs
    ADD CONSTRAINT student_orgs_pkey PRIMARY KEY (student_org_id);


--
-- Name: student_receive_info student_receive_info_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.student_receive_info
    ADD CONSTRAINT student_receive_info_pkey PRIMARY KEY (id);


--
-- Name: survey survey_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.survey
    ADD CONSTRAINT survey_pkey PRIMARY KEY (survey_id);


--
-- Name: survey_reports survey_reports_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.survey_reports
    ADD CONSTRAINT survey_reports_pkey PRIMARY KEY (report_id);


--
-- Name: survey_reports survey_reports_survey_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.survey_reports
    ADD CONSTRAINT survey_reports_survey_id_key UNIQUE (survey_id);


--
-- Name: survey_responses survey_responses_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.survey_responses
    ADD CONSTRAINT survey_responses_pkey PRIMARY KEY (response_id);


--
-- Name: survey_templates survey_templates_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.survey_templates
    ADD CONSTRAINT survey_templates_pkey PRIMARY KEY (survey_id);


--
-- Name: users uk_users_username; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk_users_username UNIQUE (username);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (user_id);

--
-- Name: campaigns fk12dysy16g5fbi4u8dycry1w2u; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.campaigns
    ADD CONSTRAINT fk12dysy16g5fbi4u8dycry1w2u FOREIGN KEY (company_id) REFERENCES public.companies(company_id);


--
-- Name: sampling_reports fk2858543tkl0adetl3pfr888xq; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sampling_reports
    ADD CONSTRAINT fk2858543tkl0adetl3pfr888xq FOREIGN KEY (campaign_id) REFERENCES public.campaigns(campaign_id);


--
-- Name: qna_questions fk2x75alelgbtgrra2hcrjkplmt; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.qna_questions
    ADD CONSTRAINT fk2x75alelgbtgrra2hcrjkplmt FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- Name: qna_answers fk36qfjq7pxcn77l9oym1bebpi3; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.qna_answers
    ADD CONSTRAINT fk36qfjq7pxcn77l9oym1bebpi3 FOREIGN KEY (question_id) REFERENCES public.qna_questions(question_id);


--
-- Name: survey_responses fk40a42uy0m0jl4timgsq21n9tx; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.survey_responses
    ADD CONSTRAINT fk40a42uy0m0jl4timgsq21n9tx FOREIGN KEY (survey_id) REFERENCES public.survey_templates(survey_id);


--
-- Name: content_uploads fk4s31enf35xqbsmk1dkso3xkgg; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.content_uploads
    ADD CONSTRAINT fk4s31enf35xqbsmk1dkso3xkgg FOREIGN KEY (collaboration_id) REFERENCES public.collaborations(collaboration_id);


--
-- Name: company_contacts fk5a8peljwaldko3px1k3dxj5v4; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.company_contacts
    ADD CONSTRAINT fk5a8peljwaldko3px1k3dxj5v4 FOREIGN KEY (company_id) REFERENCES public.companies(company_id);


--
-- Name: sampling_target_selection fk63b10e9lbvst0f5widcju64co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sampling_target_selection
    ADD CONSTRAINT fk63b10e9lbvst0f5widcju64co FOREIGN KEY (target_keyword_id) REFERENCES public.sampling_target_keyword(target_keyword_id);


--
-- Name: matching_messages fk64a0bryvw2cwguh5jpvi185a1; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.matching_messages
    ADD CONSTRAINT fk64a0bryvw2cwguh5jpvi185a1 FOREIGN KEY (matching_id) REFERENCES public.matching_requests(matching_id);


--
-- Name: receipt_confirmations fk6arh137hmvq7siwf865q4kadl; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.receipt_confirmations
    ADD CONSTRAINT fk6arh137hmvq7siwf865q4kadl FOREIGN KEY (collaboration_id) REFERENCES public.collaborations(collaboration_id);


--
-- Name: business_registrations fk6m0ej3foacqnqq3ai0y61drnl; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.business_registrations
    ADD CONSTRAINT fk6m0ej3foacqnqq3ai0y61drnl FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- Name: campaign_targets fk7146946w53bnukrycvh9te9kk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.campaign_targets
    ADD CONSTRAINT fk7146946w53bnukrycvh9te9kk FOREIGN KEY (hashtag_id) REFERENCES public.hashtags(hashtag_id);


--
-- Name: collaboration_proposals fk7kwnjpd53m5fx3kjcf84db2lw; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.collaboration_proposals
    ADD CONSTRAINT fk7kwnjpd53m5fx3kjcf84db2lw FOREIGN KEY (company_id) REFERENCES public.companies(company_id);


--
-- Name: matching_requests fk7x4wj1lhbdxobhai1ryflytcn; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.matching_requests
    ADD CONSTRAINT fk7x4wj1lhbdxobhai1ryflytcn FOREIGN KEY (campaign_id) REFERENCES public.campaigns(campaign_id);


--
-- Name: contracts fk87s25mc5y3rovlo01xfor9iax; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.contracts
    ADD CONSTRAINT fk87s25mc5y3rovlo01xfor9iax FOREIGN KEY (matching_id) REFERENCES public.matching_requests(matching_id);


--
-- Name: partnership_requests fk8jlf0uax4v0fb44vqcx7hctps; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.partnership_requests
    ADD CONSTRAINT fk8jlf0uax4v0fb44vqcx7hctps FOREIGN KEY (industry_id) REFERENCES public.industries(industry_id);


--
-- Name: qna_answers fk8tttwtftpj8c3369wyn6rhufh; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.qna_answers
    ADD CONSTRAINT fk8tttwtftpj8c3369wyn6rhufh FOREIGN KEY (admin_id) REFERENCES public.users(user_id);


--
-- Name: sampling_reports fk9bbx8bormgkfeymlxuk367d8x; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sampling_reports
    ADD CONSTRAINT fk9bbx8bormgkfeymlxuk367d8x FOREIGN KEY (survey_id) REFERENCES public.survey(survey_id);


--
-- Name: companies fk9l5d0fem75e59uwf9upwuf9du; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.companies
    ADD CONSTRAINT fk9l5d0fem75e59uwf9upwuf9du FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- Name: partnership_requests fk9xvqcynnm4a7k94ayr1u5w2ut; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.partnership_requests
    ADD CONSTRAINT fk9xvqcynnm4a7k94ayr1u5w2ut FOREIGN KEY (company_id) REFERENCES public.companies(company_id);


--
-- Name: sampling_request fkaaokoanansvgr0d19oy9kqqo1; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sampling_request
    ADD CONSTRAINT fkaaokoanansvgr0d19oy9kqqo1 FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- Name: product_infos fkbsikoer4ru1d08jm4rm4axh9i; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.product_infos
    ADD CONSTRAINT fkbsikoer4ru1d08jm4rm4axh9i FOREIGN KEY (collaboration_id) REFERENCES public.collaborations(collaboration_id);


--
-- Name: sampling_report_media fkc8ah712d094scjv0d4gv8weww; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sampling_report_media
    ADD CONSTRAINT fkc8ah712d094scjv0d4gv8weww FOREIGN KEY (report_id) REFERENCES public.sampling_reports(report_id);


--
-- Name: local_credentials fkc8ctcri3oxbshvrc0yoxpyh3x; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.local_credentials
    ADD CONSTRAINT fkc8ctcri3oxbshvrc0yoxpyh3x FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- Name: collaborations fkctmw1stvryr9ybn61b4yvx12f; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.collaborations
    ADD CONSTRAINT fkctmw1stvryr9ybn61b4yvx12f FOREIGN KEY (matching_id) REFERENCES public.matching_requests(matching_id);


--
-- Name: shipping_info fkcyt709w2xiwf1kxfmgyqkjnxs; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.shipping_info
    ADD CONSTRAINT fkcyt709w2xiwf1kxfmgyqkjnxs FOREIGN KEY (collaboration_id) REFERENCES public.collaborations(collaboration_id);


--
-- Name: payments fkd7gx3doh12b2qx2b9j2e1dsxe; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT fkd7gx3doh12b2qx2b9j2e1dsxe FOREIGN KEY (company_id) REFERENCES public.companies(company_id);


--
-- Name: collaboration_tasks fkdchdexlxl9annf3fqvbqgk37b; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.collaboration_tasks
    ADD CONSTRAINT fkdchdexlxl9annf3fqvbqgk37b FOREIGN KEY (collaboration_id) REFERENCES public.collaborations(collaboration_id);


--
-- Name: student_org_histories fkdddgt7jxx5eht7m2milcq7m2o; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.student_org_histories
    ADD CONSTRAINT fkdddgt7jxx5eht7m2milcq7m2o FOREIGN KEY (student_org_id) REFERENCES public.student_orgs(student_org_id);


--
-- Name: receipts fke5hlg1yak63f6ldrgiargtph5; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.receipts
    ADD CONSTRAINT fke5hlg1yak63f6ldrgiargtph5 FOREIGN KEY (matching_id) REFERENCES public.matching_requests(matching_id);


--
-- Name: payments fked69k88woxxuf1aqm261l3x0f; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT fked69k88woxxuf1aqm261l3x0f FOREIGN KEY (method_id) REFERENCES public.payment_methods(method_id);


--
-- Name: campaigns fkeldoka4tjl4qlyu8fs6mh5r3u; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.campaigns
    ADD CONSTRAINT fkeldoka4tjl4qlyu8fs6mh5r3u FOREIGN KEY (student_org_id) REFERENCES public.student_orgs(student_org_id);


--
-- Name: payment_methods fkeq7xs022pd07hj7osgkvmp9d; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.payment_methods
    ADD CONSTRAINT fkeq7xs022pd07hj7osgkvmp9d FOREIGN KEY (company_id) REFERENCES public.companies(company_id);


--
-- Name: collaboration_proposals fkfb2rcqvxa4q7iv0v0fefjni9e; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.collaboration_proposals
    ADD CONSTRAINT fkfb2rcqvxa4q7iv0v0fefjni9e FOREIGN KEY (industry_id) REFERENCES public.industries(industry_id);


--
-- Name: file_uploads fkfp20hhfo6lls9745pda6jf5mc; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.file_uploads
    ADD CONSTRAINT fkfp20hhfo6lls9745pda6jf5mc FOREIGN KEY (uploader_id) REFERENCES public.users(user_id);


--
-- Name: campaign_hashtags fkg219w59fxt3gupsgcdj9vp0sk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.campaign_hashtags
    ADD CONSTRAINT fkg219w59fxt3gupsgcdj9vp0sk FOREIGN KEY (campaign_id) REFERENCES public.campaigns(campaign_id);


--
-- Name: survey_reports fkgi3fa41mixocwnrq39vyhvwk7; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.survey_reports
    ADD CONSTRAINT fkgi3fa41mixocwnrq39vyhvwk7 FOREIGN KEY (survey_id) REFERENCES public.survey(survey_id);


--
-- Name: student_org_keywords fkgupym7hndw472ttm4pkasr5dh; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.student_org_keywords
    ADD CONSTRAINT fkgupym7hndw472ttm4pkasr5dh FOREIGN KEY (hashtag_id) REFERENCES public.hashtags(hashtag_id);


--
-- Name: sampling_report_feedback fkiplgf1aomc4gpqwxjn2ek35sq; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sampling_report_feedback
    ADD CONSTRAINT fkiplgf1aomc4gpqwxjn2ek35sq FOREIGN KEY (report_id) REFERENCES public.sampling_reports(report_id);


--
-- Name: company_profiles fkjr2y1a5kif0bg4wxilqfmtnhs; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.company_profiles
    ADD CONSTRAINT fkjr2y1a5kif0bg4wxilqfmtnhs FOREIGN KEY (company_id) REFERENCES public.companies(company_id);


--
-- Name: matching_requests fkkqhbgtu2p6gy258w5qoqk0go3; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.matching_requests
    ADD CONSTRAINT fkkqhbgtu2p6gy258w5qoqk0go3 FOREIGN KEY (student_org_id) REFERENCES public.student_orgs(student_org_id);


--
-- Name: survey_templates fkl1dif3b9jxan8bem1jxb52r3x; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.survey_templates
    ADD CONSTRAINT fkl1dif3b9jxan8bem1jxb52r3x FOREIGN KEY (campaign_id) REFERENCES public.campaigns(campaign_id);


--
-- Name: sampling_target_selection fkmewsoik66wpa9a56la9mpj553; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sampling_target_selection
    ADD CONSTRAINT fkmewsoik66wpa9a56la9mpj553 FOREIGN KEY (sampling_request_id) REFERENCES public.sampling_request(sampling_request_id);


--
-- Name: company_settings fkmooaravxwx9tubb173apgo343; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.company_settings
    ADD CONSTRAINT fkmooaravxwx9tubb173apgo343 FOREIGN KEY (company_id) REFERENCES public.companies(company_id);


--
-- Name: student_receive_info fkmyax2v4jf19wvcmedm9u0yn3j; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.student_receive_info
    ADD CONSTRAINT fkmyax2v4jf19wvcmedm9u0yn3j FOREIGN KEY (collaboration_id) REFERENCES public.collaborations(collaboration_id);


--
-- Name: oauth_accounts fkn6j2b3ur1fcj3vkodrmqtdxmi; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.oauth_accounts
    ADD CONSTRAINT fkn6j2b3ur1fcj3vkodrmqtdxmi FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- Name: phone_verifications fknufym3qvct2xqh65r9ly52iyf; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.phone_verifications
    ADD CONSTRAINT fknufym3qvct2xqh65r9ly52iyf FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- Name: campaign_industries fkogl539e5d49d5sqdrl97pfr89; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.campaign_industries
    ADD CONSTRAINT fkogl539e5d49d5sqdrl97pfr89 FOREIGN KEY (campaign_id) REFERENCES public.campaigns(campaign_id);


--
-- Name: email_verifications fkou1xuy3rdeao75p2x1v4v3xs; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.email_verifications
    ADD CONSTRAINT fkou1xuy3rdeao75p2x1v4v3xs FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- Name: users fkowofyohq0w6scxxceghglm6ix; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT fkowofyohq0w6scxxceghglm6ix FOREIGN KEY (student_org_id) REFERENCES public.student_orgs(student_org_id);


--
-- Name: student_org_contacts fkq0eu8pfs5xjjyvj20quianib; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.student_org_contacts
    ADD CONSTRAINT fkq0eu8pfs5xjjyvj20quianib FOREIGN KEY (student_org_id) REFERENCES public.student_orgs(student_org_id);


--
-- Name: invoices fkq6fs19k0gqw3rg0mb87h60h6p; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.invoices
    ADD CONSTRAINT fkq6fs19k0gqw3rg0mb87h60h6p FOREIGN KEY (payment_id) REFERENCES public.payments(payment_id);


--
-- Name: student_org_keywords fkqbthmsjug45920ct6eceqls56; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.student_org_keywords
    ADD CONSTRAINT fkqbthmsjug45920ct6eceqls56 FOREIGN KEY (student_org_id) REFERENCES public.student_orgs(student_org_id);


--
-- Name: student_org_availabilities fkr32birmdrf2v3gxo8ap1fnvpu; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.student_org_availabilities
    ADD CONSTRAINT fkr32birmdrf2v3gxo8ap1fnvpu FOREIGN KEY (student_org_id) REFERENCES public.student_orgs(student_org_id);


--
-- Name: campaign_targets fkrclwq7u1xg7rn9i2nl0wh39nm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.campaign_targets
    ADD CONSTRAINT fkrclwq7u1xg7rn9i2nl0wh39nm FOREIGN KEY (campaign_id) REFERENCES public.campaigns(campaign_id);


--
-- Name: collaboration_reports fkrehy4ms1q3hp86mid98rb424x; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.collaboration_reports
    ADD CONSTRAINT fkrehy4ms1q3hp86mid98rb424x FOREIGN KEY (collaboration_id) REFERENCES public.collaborations(collaboration_id);


--
-- Name: campaign_industries fkrn55avplnq2k41eny9akieb9s; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.campaign_industries
    ADD CONSTRAINT fkrn55avplnq2k41eny9akieb9s FOREIGN KEY (industry_id) REFERENCES public.industries(industry_id);


--
-- Name: refund_requests fkrngyk3a1ipu99kdcanl7a4jy5; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.refund_requests
    ADD CONSTRAINT fkrngyk3a1ipu99kdcanl7a4jy5 FOREIGN KEY (payment_id) REFERENCES public.payments(payment_id);


--
-- Name: login_audits fkrrof8076dr9yfkrbqqksnwb43; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.login_audits
    ADD CONSTRAINT fkrrof8076dr9yfkrbqqksnwb43 FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- Name: payments fks7njvtulxuac7jpbgt9i3f5yi; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT fks7njvtulxuac7jpbgt9i3f5yi FOREIGN KEY (campaign_id) REFERENCES public.campaigns(campaign_id);


--
-- Name: campaign_hashtags fksarf8fotmon2f4vn17h1kbpdc; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.campaign_hashtags
    ADD CONSTRAINT fksarf8fotmon2f4vn17h1kbpdc FOREIGN KEY (hashtag_id) REFERENCES public.hashtags(hashtag_id);


--
-- Name: companies fksmvt41c2quaagfwsorsfexn6u; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.companies
    ADD CONSTRAINT fksmvt41c2quaagfwsorsfexn6u FOREIGN KEY (industry_id) REFERENCES public.industries(industry_id);


--
-- Name: survey fkt308b5fe3kyj2xhrbpn80v0l6; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.survey
    ADD CONSTRAINT fkt308b5fe3kyj2xhrbpn80v0l6 FOREIGN KEY (student_org_id) REFERENCES public.student_orgs(student_org_id);


--
-- PostgreSQL database dump complete
--